name: build-dgraph

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build-dgraph:
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16.13.1'

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - run: yarn install
            - run: yarn build-deps
            # - run: yarn backend-build
            - run: yarn electron-dist

            # - name: Upload backend as artifact
            #   uses: actions/upload-artifact@v2
            #   with:
            #       name: unigraph_backend
            #       path: ./dist/dgraph_linux_amd64
            #       if-no-files-found: error

            - name: Upload frontend as artifact
              uses: actions/upload-artifact@v2
              with:
                  name: unigraph_frontend
                  path: ./packages/unigraph-dev-electron/dist/Unigraph-0.1.0.AppImage
                  if-no-files-found: error

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      ./packages/unigraph-dev-electron/dist/Unigraph-0.1.0.AppImage
                  fail_on_unmatched_files: true
