name: test

on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  test-common-lib:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - run: cd packages/unigraph-dev-common/
      
      - run: npx jest